name: Restart Service

on:
  workflow_dispatch:
    inputs:
      motivo:
        description: Motivo del Restart
        required: false
        type: string
        default: ''

      test:
        description: Test
        required: true
        type: boolean
        default: false

      qa:
        description: QA
        required: true
        type: boolean
        default: false

      prod:
        description: Production
        required: true
        type: boolean
        default: false

jobs:
  restart_service:
    name: 🦖 Restart Service
    uses: infrastructure-services/workflow/.github/workflows/restart-service.yml@main
    with:
      motivo: ${{ inputs.motivo }}
      test: ${{ inputs.test }}
      qa: ${{ inputs.qa }}
      prod: ${{ inputs.prod }}
    secrets: inherit